### ISSUE TITLE
Unable to fetch data from sqlite_db

### ISSUE THREAD

**Issue by vishy1618** [kunal/sqlite-http-basic-auth-nginx-module#1]
When incorrect user credentials are supplied the following output is obtained:

2011/05/26 10:47:04 [error] 29435#0: *1 sds:cdsds was not found in auth_table table, client: 127.0.0.1, server: localhost, request: "GET /auth/ HTTP/1.1", host: "localhost:1035"

The db is opened successfully, but on supplying the correct credentials, the following output is obtained:

2011/05/26 10:47:19 [crit] 29435#0: *1 Unable to fetch data from "/home/suvish/nginx/db/sqlite_db" database, client: 127.0.0.1, server: localhost, request: "GET /auth/ HTTP/1.1", host: "localhost:1035"

**Comment by kunal** [comment]
Which version of nginx are you using?

On Thu, May 26, 2011 at 11:26 AM, vishy1618
reply@reply.github.com
wrote:

> When incorrect user credentials are supplied the following output is obtained:
> 
> 2011/05/26 10:47:04 [error] 29435#0: *1 sds:cdsds was not found in auth_table table, client: 127.0.0.1, server: localhost, request: "GET /auth/ HTTP/1.1", host: "localhost:1035"
> 
> The db is opened successfully, but on supplying the correct credentials, the following output is obtained:
> 
> 2011/05/26 10:47:19 [crit] 29435#0: *1 Unable to fetch data from "/home/suvish/nginx/db/sqlite_db" database, client: 127.0.0.1, server: localhost, request: "GET /auth/ HTTP/1.1", host: "localhost:1035"
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kunal/sqlite-http-basic-auth-nginx-module/issues/1

## 

Thanx,
Kunal

Projects: http://gitorious.org/~kunalbharati
Wordpress Blog: http://bharatikunal.wordpress.com/
Blogspot Blog: http://bharatikunal.blogspot.com
Twitter: http://twitter.com/kunalbharati

**Comment by vishy1618** [comment]
0.8.54

**Comment by kunal** [comment]
vishy1618,
thanx for the patch
